services:
  reminderbot:
    build:
      context: ./
      target: reminderbot
    image: reminderbot-reminderbot
    container_name: reminderbot
    volumes:
      - ./ReminderBotConfig:/opt/reminderbot/ReminderBotConfig
    restart: unless-stopped